export interface MeasurementFields {
  gender: "male" | "female";
  armhole: string | null;
  bicep: string | null;
  chest: string | null;
  cuff_width: string | null;
  hip: string | null;
  kameez_back_length: string | null;
  kameez_front_length: string | null;
  kameez_length: string | null;
  neck_circumference: string | null;
  neck_depth_back: string | null;
  neck_depth_front: string | null;
  shoulder_width: string | null;
  side_slit_length: string | null;
  sleeve_length: string | null;
  waist: string | null;
  elbow: string | null;
  cross_back: string | null;
  shoulder_slope: string | null;
  collar_size: string | null;

  ankle_width: string | null;
  crotch_depth: string | null;
  flare_width: string | null;
  knee: string | null;
  salwar_hip: string | null;
  salwar_length: string | null;
  salwar_waist: string | null;
  thigh: string | null;
  bottom_opening: string | null;
  rise_front: string | null;
  rise_back: string | null;

  bust: string | null;
  shoulder_to_bust_point: string | null;
  bust_point_to_bust_point: string | null;
  under_bust: string | null;
  dart_length_front: string | null;
  dart_length_back: string | null;
  hip_depth: string | null;
  flare_length: string | null;
}
